version: "3"
services:
  app:
    container_name: app
    build: .
    #image: kgalb01/geosoft_task_7
    ports:
      - "3000:3000"
    depends_on:
      - mongodbservice
  mongodbservice:
    container_name: mongo
    image: mongo # to be retrieved from dockerhub
    ports:
      - '27017:27017' # forward mongod port
    volumes:
       # - ./data:/data/db
       - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - '8888:8081'
    depends_on:
      - mongodbservice